---
- name: ansi
  hosts: localhost
  tasks:
  - name: install
    yum:
      name: httpd
      state: present
  - name: service
    service:
      name: httpd
      state: started
      enabled: true

  - name: copy
    copy:
      src: ./index.html
      dest: /var/www/html/index.html
